name: causewell
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  bloc: ^3.0.0
  cached_network_image: 2.2.0+1
  cloud_firestore: ^0.14.4
  cloud_functions: ^0.7.2
  cupertino_icons: ^0.1.2
  device_info: 0.4.2+4
  dio: ^3.0.9
  dio_flutter_transformer: ^3.0.2
  equatable: ^1.0.0
  file_picker: 1.6.3+2
  firebase_auth: ^0.18.4
  firebase_core: ^0.5.3
  firebase_crashlytics: 0.1.3
  firebase_messaging: ^5.1.6
  firebase_storage: ^5.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^3.2.0
  flutter_form_builder: ^3.10.0
  flutter_html: ^0.11.1
  flutter_launcher_icons: 0.7.5
  flutter_rating_bar: 3.0.1+1
  flutter_staggered_grid_view: 0.3.0
  flutter_svg: 0.17.3+1
  get: ^3.13.2
  google_fonts: 0.3.9
  html_unescape: 1.0.1+3
  http: 0.12.0+4
  image_picker: 0.6.6+1
  in_app_purchase: 0.3.4+1
  inject:
    path: ./inject.dart/package/inject
  json_annotation: 3.0.1
  meta: ^1.1.6
  overlay_support: 1.0.4
  package_info: ^0.4.1
  page_transition: 1.1.5
  path_provider: 1.6.9
  rxdart: ^0.23.1
  share: 0.6.3+6
  shared_preferences: 0.5.6+2
  shimmer: 1.1.0
  transparent_image: 1.0.0
  url_launcher: 5.4.5
  video_player: 0.10.9
  youtube_player_flutter: 6.1.1

dev_dependencies:
  build_runner: 1.7.4
  flutter_test:
    sdk: flutter
  inject_generator:
    path: ./inject.dart/package/inject_generator

  json_serializable: 3.2.5

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/localization/

flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/images/logo.png'
